spring.application.name=algoritmando

# H2 Database (em memoria)
spring.datasource.url=jdbc:h2:mem:algoritmando
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# Console do H2 (visualizacao do banco no navegador)
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Porta
server.port=8080